package main

var (
	testLoad = &SystemLoads{
		noOfNodes:                   8000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "4MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}

	testLoad3000NodesWith4MbReport = &SystemLoads{
		noOfNodes:                   3000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "4MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad3000NodesWith2MbReport = &SystemLoads{
		noOfNodes:                   3000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "2MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad3000NodesWith1MbReport = &SystemLoads{
		noOfNodes:                   3000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "1MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}

	testLoad5000NodesWith4MbReport = &SystemLoads{
		noOfNodes:                   5000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "4MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad5000NodesWith2MbReport = &SystemLoads{
		noOfNodes:                   5000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "2MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad5000NodesWith1MbReport = &SystemLoads{
		noOfNodes:                   5000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "1MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad10000NodesWith4MbReport = &SystemLoads{
		noOfNodes:                   10000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "4MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad10000NodesWith2MbReport = &SystemLoads{
		noOfNodes:                   10000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "2MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad10000NodesWith1MbReport = &SystemLoads{
		noOfNodes:                   10000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "1MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad20000NodesWith4MbReport = &SystemLoads{
		noOfNodes:                   20000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "4MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad20000NodesWith2MbReport = &SystemLoads{
		noOfNodes:                   20000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "2MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad20000NodesWith1MbReport = &SystemLoads{
		noOfNodes:                   20000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "1MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad40000NodesWith4MbReport = &SystemLoads{
		noOfNodes:                   40000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "4MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad40000NodesWith2MbReport = &SystemLoads{
		noOfNodes:                   40000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "2MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad40000NodesWith1MbReport = &SystemLoads{
		noOfNodes:                   40000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "1MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad80000NodesWith4MbReport = &SystemLoads{
		noOfNodes:                   80000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "4MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad80000NodesWith2MbReport = &SystemLoads{
		noOfNodes:                   80000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_HOUR,
		complianceScanReportSize:    "2MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
	testLoad80000NodesWith1MbReport = &SystemLoads{
		noOfNodes:                   80000,
		noOfComplianceScan:          1,
		frequencyOfComplianceScan:   FREQ_PER_DAY,
		complianceScanReportSize:    "4MB",
		noOfClientRun:               1,
		frequencyOfClientRun:        FREQ_PER_HOUR,
		clientRunSize:               "300KB",
		noOfEventFeed:               1,
		frequencyOfEventFeed:        FREQ_PER_HOUR,
		eventFeedUpdateSize:         "2KB",
		DataRetentionPolicyInDays:   30,
		noOfShardsInOpensearchIndex: 2,
	}
)
